{{ if .Values.network }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-chart.name" . }}
  labels:
{{ include "generic-chart.labels" . | indent 4 }}
{{- if gt (len .Values.service.annotations) 0 }}
  annotations:
{{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $val := .Values.network }}
  {{- if $val.servicePort}}
  - name: {{ $key }}    
    port: {{ $val.servicePort }}
    protocol: {{ default "TCP" $val.protocol }}
    targetPort: {{ default $key $val.targetPort }}
  {{- end }}
  {{- end }}
  selector:
    app: {{ include "generic-chart.name" . }}
    release: {{ .Release.Name }}
{{- end }}